version: 2

models:
  - name: mart_sales_summary
    description: Aggregated sales data summarizing total spent and total orders per customer.
    columns:
      - name: customer_id
        description: Unique identifier for the customer.
        tests:
          - not_null
          - unique
      - name: total_spent
        description: Total amount spent by the customer.
        tests:
          - not_null
      - name: total_orders
        description: Total number of orders placed by the customer.
        tests:
          - not_null

  - name: mart_sales_detailed
    description: Detailed sales data including running totals and order numbers for each customer.
    columns:
      - name: sales_id
        description: Unique identifier for the sale.
        tests:
          - not_null
          - unique
      - name: customer_id
        description: Unique identifier for the customer.
        tests:
          - not_null
      - name: order_number
        description: Sequential order number for the customer's purchases.
        tests:
          - not_null
      - name: running_total
        description: Running total of the customer's spending.
        tests:
          - not_null

  - name: mart_product_performance
    description: Performance metrics for products, including total sales and revenue.
    columns:
      - name: product_id
        description: Unique identifier for the product.
        tests:
          - not_null
          - unique
      - name: total_sales
        description: Total number of sales for the product.
        tests:
          - not_null
      - name: total_revenue
        description: Total revenue generated by the product.
        tests:
          - not_null

  - name: mart_customer_lifetime_value
    description: Customer lifetime value metrics, including total revenue and average order value.
    columns:
      - name: customer_id
        description: Unique identifier for the customer.
        tests:
          - not_null
          - unique
      - name: lifetime_revenue
        description: Total revenue generated by the customer.
        tests:
          - not_null
      - name: average_order_value
        description: Average value of the customer's orders.
        tests:
          - not_null

  - name: mart_sales_by_region
    description: Sales data aggregated by region, including total revenue and order count.
    columns:
      - name: region_id
        description: Unique identifier for the region.
        tests:
          - not_null
          - unique
      - name: total_revenue
        description: Total revenue generated in the region.
        tests:
          - not_null
      - name: total_orders
        description: Total number of orders in the region.
        tests:
          - not_null

  - name: mart_monthly_sales
    description: Monthly sales data, including total revenue and order count.
    columns:
      - name: month
        description: Month of the sales data.
        tests:
          - not_null
      - name: total_revenue
        description: Total revenue generated in the month.
        tests:
          - not_null
      - name: total_orders
        description: Total number of orders in the month.
        tests:
          - not_null

  - name: mart_top_customers
    description: Data for top customers based on total revenue and order count.
    columns:
      - name: customer_id
        description: Unique identifier for the customer.
        tests:
          - not_null
          - unique
      - name: total_revenue
        description: Total revenue generated by the customer.
        tests:
          - not_null
      - name: total_orders
        description: Total number of orders placed by the customer.
        tests:
          - not_null

  - name: mart_sales_trends
    description: Sales trends over time, including revenue and order count.
    columns:
      - name: date
        description: Date of the sales data.
        tests:
          - not_null
      - name: total_revenue
        description: Total revenue generated on the date.
        tests:
          - not_null
      - name: total_orders
        description: Total number of orders on the date.
        tests:
          - not_null